// Generated by https://quicktype.io

export interface SearchResponse {
  statuses:        Status[];
  search_metadata: SearchMetadata;
}

export interface SearchMetadata {
  completed_in: number;
  max_id:       number;
  max_id_str:   string;
  next_results: string;
  query:        string;
  refresh_url:  string;
  count:        number;
  since_id:     number;
  since_id_str: string;
}

export interface Status {
  created_at:                Date;
  id:                        number;
  id_str:                    string;
  text:                      string;
  truncated:                 boolean;
  entities:                  StatusEntities;
  extended_entities?:        StatusExtendedEntities;
  metadata:                  Metadata;
  source:                    string;
  in_reply_to_status_id:     number | null;
  in_reply_to_status_id_str: null | string;
  in_reply_to_user_id:       number | null;
  in_reply_to_user_id_str:   null | string;
  in_reply_to_screen_name:   null | string;
  user:                      User;
  geo:                       null;
  coordinates:               null;
  place:                     null;
  contributors:              null;
  retweeted_status?:         RetweetedStatus;
  is_quote_status:           boolean;
  retweet_count:             number;
  favorite_count:            number;
  favorited:                 boolean;
  retweeted:                 boolean;
  possibly_sensitive?:       boolean;
  lang:                      Lang;
}

export interface StatusEntities {
  hashtags:      any[];
  symbols:       any[];
  user_mentions: UserMention[];
  urls:          URL[];
  media?:        PurpleMedia[];
}

export interface PurpleMedia {
  id:                   number;
  id_str:               string;
  indices:              number[];
  media_url:            string;
  media_url_https:      string;
  url:                  string;
  display_url:          string;
  expanded_url:         string;
  type:                 string;
  sizes:                Sizes;
  source_status_id:     number;
  source_status_id_str: string;
  source_user_id:       number;
  source_user_id_str:   string;
}

export interface Sizes {
  small:  Large;
  thumb:  Large;
  medium: Large;
  large:  Large;
}

export interface Large {
  w:      number;
  h:      number;
  resize: Resize;
}

export enum Resize {
  Crop = "crop",
  Fit = "fit",
}

export interface URL {
  url:          string;
  expanded_url: string;
  display_url:  string;
  indices:      number[];
}

export interface UserMention {
  screen_name: string;
  name:        string;
  id:          number;
  id_str:      string;
  indices:     number[];
}

export interface StatusExtendedEntities {
  media: PurpleMedia[];
}


export interface Metadata {
  iso_language_code: string;
  result_type: string;
}

export interface RetweetedStatus {
  created_at:                string;
  id:                        number;
  id_str:                    string;
  text:                      string;
  truncated:                 boolean;
  entities:                  RetweetedStatusEntities;
  extended_entities?:        RetweetedStatusExtendedEntities;
  metadata:                  Metadata;
  source:                    string;
  in_reply_to_status_id:     null;
  in_reply_to_status_id_str: null;
  in_reply_to_user_id:       null;
  in_reply_to_user_id_str:   null;
  in_reply_to_screen_name:   null;
  user:                      User;
  geo:                       null;
  coordinates:               null;
  place:                     null;
  contributors:              null;
  is_quote_status:           boolean;
  retweet_count:             number;
  favorite_count:            number;
  favorited:                 boolean;
  retweeted:                 boolean;
  possibly_sensitive?:       boolean;
  lang:                      string;
}

export interface RetweetedStatusEntities {
  hashtags:      any[];
  symbols:       any[];
  user_mentions: any[];
  urls:          any[];
  media?:        FluffyMedia[];
}

export interface FluffyMedia {
  id:              number;
  id_str:          string;
  indices:         number[];
  media_url:       string;
  media_url_https: string;
  url:             string;
  display_url:     string;
  expanded_url:    string;
  type:            string;
  sizes:           Sizes;
}

export interface RetweetedStatusExtendedEntities {
  media: FluffyMedia[];
}

export interface User {
  id:                                 number;
  id_str:                             string;
  name:                               string;
  screen_name:                        string;
  location:                           string;
  description:                        string;
  url:                                null | string;
  entities:                           UserEntities;
  protected:                          boolean;
  followers_count:                    number;
  friends_count:                      number;
  listed_count:                       number;
  created_at:                         string;
  favourites_count:                   number;
  utc_offset:                         null;
  time_zone:                          null;
  geo_enabled:                        boolean;
  verified:                           boolean;
  statuses_count:                     number;
  lang:                               null;
  contributors_enabled:               boolean;
  is_translator:                      boolean;
  is_translation_enabled:             boolean;
  profile_background_color:           ProfileColor;
  profile_background_image_url:       null | string;
  profile_background_image_url_https: null | string;
  profile_background_tile:            boolean;
  profile_image_url:                  string;
  profile_image_url_https:            string;
  profile_banner_url?:                string;
  profile_link_color:                 string;
  profile_sidebar_border_color:       string;
  profile_sidebar_fill_color:         string;
  profile_text_color:                 string;
  profile_use_background_image:       boolean;
  has_extended_profile:               boolean;
  default_profile:                    boolean;
  default_profile_image:              boolean;
  following:                          null;
  follow_request_sent:                null;
  notifications:                      null;
  translator_type:                    string;
}

export interface UserEntities {
  url?:        Description;
  description: Description;
}

export interface Description {
  urls: URL[];
}

